---
title: "godaddy nested data"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file=file.path(dirname(input_file), out_dir, 'index.html))})

---

```{r}
library(readr)
census_starter <- read_csv("GoDaddy/godaddy-microbusiness-density-forecasting/census_starter.csv")
train <- read_csv("GoDaddy/godaddy-microbusiness-density-forecasting/train.csv")
test <- read_csv("GoDaddy/godaddy-microbusiness-density-forecasting/test.csv")
```

### Nested Data

# Nested Data Frames by County

```{r}
library(modelr)
library(tidyverse)
library(dplyr)
library(gapminder)
```

#Nest

```{r}
by_county <- train %>%
  group_by(cfips, state) %>%
  nest()
```

#Model-fitting function

```{r}
county_model <- function(df) {
  lm(microbusiness_density ~ first_day_of_month, data = df)
}
```

#Apply to each element

```{r}
models <- map(by_county$data, county_model)
```

#Adding models to dataframe

```{r}
by_county <- by_county %>%
  mutate(model = map(data, county_model))
```

```{r}
by_county %>% 
  filter(state == "Texas")
```

#Adding residuals of each model

```{r}
by_county <- by_county %>%
  mutate(
    resids = map2(data, model, add_residuals)
  )
```

#Unnesting

```{r}
resids <- unnest(by_county, resids)
```

#Plotting the residuals

```{r}
resids %>%
  ggplot(aes(first_day_of_month, resid)) +
  geom_line(aes(group = cfips), alpha = 1/3) +
  geom_smooth(se = FALSE)

```

#Facetting by state

```{r}
resids %>% 
  ggplot(aes(first_day_of_month, resid, group = cfips)) +
  geom_line(alpha = 1/3) +
  facet_wrap(~state)
```

#Extracting model quality

```{r}
glance <- by_county %>% 
  mutate(glance = map(model, broom::glance)) %>%
  unnest(glance)
```

#Arrange by R square

```{r}
glance %>% 
  arrange(r.squared)
```

#Plot worst r squared

```{r}
glance %>% 
  ggplot(aes(state, r.squared)) +
  geom_jitter(width = 0.5) +
  theme(axis.text.x = element_text(angle = 90))
```

#Fable #Load packages

```{r eval=FALSE, include=FALSE}
library(fable)
library(tsibble)
library(tsibbledata)
library(lubridate)
library(dplyr)
```

#Keeping tibble format

```{r eval=FALSE, include=FALSE}
texas_001 <- by_county %>%
  filter(
    state %in% c("Texas"),
    cfips == "48001"
  )
```

```{r eval=FALSE, include=FALSE}
by_county %>%
  filter(
    state %in% c("Texas"),
    cfips == "48001"
  ) %>%
  model(
    ets = ETS(box_cox(microbusiness_density, 0.3)),
    arima = ARIMA(log(microbusiness_density)),
    snaive = SNAIVE(microbusiness_density)
  ) %>%
  forecast(h ="2 months") %>%
  autoplot(filter(by_county))
```

t
